from pydantic import BaseModel, ConfigDict
from datetime import date
from typing import Optional

class CusQuotationBase(BaseModel):
    quotation_id: Optional[int] = None  # Auto-generated by DB, so optional in Base
    quotation_no: str
    
    salesperson: Optional[str] = None
    subject: Optional[str] = None
    amount_including_gst: Optional[int] = None
    without_gst: Optional[int] = None
    gst_amount: Optional[int] = None
    amount_with_gst: Optional[int] = None
    warranty_guarantee: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[str] = None
    date: Optional[date] = None
    client_id: int  # Required to link client

class CusQuotationCreate(BaseModel):
    quotation_no: str
    salesperson: Optional[str] = None
    subject: Optional[str] = None
    amount_including_gst: Optional[int] = None
    without_gst: Optional[int] = None
    gst_amount: Optional[int] = None
    amount_with_gst: Optional[int] = None
    warranty_guarantee: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[str] = None
    date: Optional[date] = None
    client_id: int

class CusQuotationUpdate(CusQuotationBase):
    pass

class CusQuotation(CusQuotationBase):
    model_config = ConfigDict(from_attributes=True)  # ORM compatibility
