from pydantic import BaseModel, ConfigDict
from datetime import date
from typing import Optional

class QuotationBase(BaseModel):
    quotation_id: Optional[int] = None  # Auto-generated by DB, optional here
    quotation_no: str
    salesperson: Optional[str] = None
    subject: Optional[str] = None
    amount_including_gst: Optional[int] = None
    without_gst: Optional[int] = None
    gst_amount: Optional[int] = None
    amount_with_gst: Optional[int] = None
    warranty_guarantee: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[bool] = None
    date: Optional[date] = None
    client_id: int  # Required to link to client

class QuotationCreate(QuotationBase):
    pass  # All fields required for creation are inherited

class QuotationUpdate(QuotationBase):
    pass  # Same fields for updates

class Quotation(QuotationBase):
    model_config = ConfigDict(from_attributes=True)  # ORM compatibility
