from pydantic import BaseModel, ConfigDict
from datetime import date
from typing import Optional

class QuotationBase(BaseModel):
    quotation_id: Optional[int] = None  # Auto-generated by DB, so optional in Base
    quotation_no: str
    salesperson: Optional[str] = None
    subject: Optional[str] = None
    amount_including_GST: Optional[int] = None
    without_GST: Optional[int] = None
    GST_ammount: Optional[int] = None
    amount_withGST: Optional[int] = None
    warranty_guarantee: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[bool] = None
    date: Optional[date] = None
    client_id: int  # Required to link client

class QuotationCreate(BaseModel):
    quotation_no: str
    salesperson: Optional[str] = None
    subject: Optional[str] = None
    amount_including_GST: Optional[int] = None
    without_GST: Optional[int] = None
    GST_ammount: Optional[int] = None
    amount_withGST: Optional[int] = None
    warranty_guarantee: Optional[str] = None
    remarks: Optional[str] = None
    status: Optional[bool] = None
    date: Optional[date] = None
    client_id: int

class QuotationUpdate(QuotationBase):
    pass

class Quotation(QuotationBase):
    model_config = ConfigDict(from_attributes=True)  # ORM compatibility
