name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  setup_database:
    name: Setup Database
    runs-on: ubuntu-latest
    needs: install_dependencies  # Run after dependencies are installed

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Database Connection
        env:
          DATABASE_URL: postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432/${{ env.POSTGRES_DB }}
        run: echo "Database is ready to use."

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [install_dependencies, setup_database]  # Run after dependencies and DB setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests with Pytest
        env:
          DATABASE_URL: postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432/${{ env.POSTGRES_DB }}
        run: |
          pytest --disable-warnings

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: run_tests  # Deploy only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production (Example)
        run: echo "Deploying FastAPI application..."
